name: Compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        git submodule update --init --recursive --depth 1
        export KBUILD_BUILD_USER="Revanth"
        export ARCH=arm64
        export SUBARCH=arm64
        export ANDROID_MAJOR_VERSION=q
        DEFCONFIG=exynos9610-m31nsxx_defconfig
        make $DEFCONFIG
        make -j"$PROCS"
