name: Compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        git submodule update --init --recursive --depth 1
        chmod a+x m31.sh
        ./m31.sh
